Marvel of the Universe/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Marvel_of_the_Universe.Models
{
    public class Comment
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string UserName { get; set; }
        public int? HeroeId { get; set; }
        public int? MovieId { get; set; }
        public Heroe Heroe { get; set; }
        public Movie Movie { get; set; }
    }
}

Marvel of the Universe/Models/Heroe.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;

namespace Marvel_of_the_Universe.Models
{
    public class Heroe
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Actor { get; set; }
        public string Skills { get; set; }
        public string Image { get; set; }
        public virtual ICollection<Movie> Movies { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public Heroe()
        {
            Movies = new List<Movie>();
            Likes = new List<Like>();
            Comments = new List<Comment>();
        }
    }

}

Marvel of the Universe/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Marvel_of_the_Universe.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Genre { get; set; }
        public int YearRelease { get; set; }
        public string Image { get; set; }
        public virtual ICollection<Heroe> Heroes { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public Movie()
        {
            Heroes = new List<Heroe>();
            Likes = new List<Like>();
            Comments = new List<Comment>();
        }
    }
}

Marvel of the Universe/Controllers/MarvelController.cs
using Marvel_of_the_Universe.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MySql.Data.MySqlClient;
using System.Collections.ObjectModel;

namespace Marvel_of_the_Universe.Controllers
{
    public class MarvelController : Controller
    {
        private MarvelContext db = new MarvelContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Heroes(int page = 1)
        {
            int pageSize = 6;
            IEnumerable<Heroe> heroesOnPage = db.Heroes
                .OrderBy(x => x.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize).ToList();
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = db.Heroes.Count() };
            IndexViewHeroes ivh = new IndexViewHeroes { PageInfo = pageInfo, Heroes = heroesOnPage };
            return View(ivh);
        }
        public ActionResult Movies(int page = 1)
        {
            int pageSize = 6;
            IEnumerable<Movie> moviesOnPage = db.Movies
                .OrderBy(x => x.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize).ToList();
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = db.Movies.Count() };
            IndexViewMovies ivh = new IndexViewMovies { PageInfo = pageInfo, Movies = moviesOnPage };
            return View(ivh);
        }
        public FileResult GetImage()
        {
            return File(Server.MapPath("~/Images/Marvel.png"), "image/png");
        }
        public ActionResult Movie(long id, int list = 1)
        {
            Movie movie = db.Movies.Find(id);
            int listSize = 3;
            IEnumerable<Heroe> heroesOnList = movie.Heroes
                .OrderBy(x => x.Id)
                .Skip((list - 1) * listSize)
                .Take(listSize).ToList();
            ListInfo listInfo = new ListInfo { ListNumber = list, ListSize = listSize, TotalItems = movie.Heroes.Count() };
            ViewMovie vm = new ViewMovie { ListInfo = listInfo, Movie = movie, Heroes = heroesOnList };
            return View(vm);
        }
        public ActionResult Heroe(long id,int list = 1)
        {
            Heroe heroe = db.Heroes.Find(id);
            int listSize = 3;
            IEnumerable<Movie> moviesOnList = heroe.Movies
                .OrderBy(x => x.Id)
                .Skip((list - 1) * listSize)
                .Take(listSize).ToList();
            ListInfo listInfo = new ListInfo { ListNumber = list, ListSize = listSize, TotalItems = heroe.Movies.Count() };
            ViewHeroe vh = new ViewHeroe { ListInfo = listInfo, Heroe = heroe, Movies = moviesOnList };
            return View(vh);
        }
        [HttpPost]
        public ActionResult NewComment(Comment comment)
        {
            User user = null;
            using (UserContext db = new UserContext())
            {
                user = db.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            }
            if (user == null)
            {
                return Json(new { url = Url.Action("Login", "Account") });
            }
            if (comment.HeroeId != null)
            {
                Heroe heroe = db.Heroes.Find(comment.HeroeId);
                if (heroe == null)
                    return HttpNotFound();
                heroe.Comments.Add(comment);
                db.SaveChanges();
                return PartialView("Comment",comment);
            }
            else
            {
                Movie movie = db.Movies.Find(comment.MovieId);
                if (movie == null)
                    return HttpNotFound();
                movie.Comments.Add(comment);
                db.SaveChanges();
                return PartialView("Comment", comment);
            }
        }
        [HttpPost]
        public ActionResult LikeHeroe(int? heroeId)
        {
            User user = null;
            using (UserContext db = new UserContext())
            {
                user = db.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            }
            if (user == null)
            {
                return Json(new { url = Url.Action("Login","Account") });
            }
            Like like = db.Likes.Where(l => l.UserName == User.Identity.Name).FirstOrDefault();
            Heroe heroe = db.Heroes.Find(heroeId);
            if (heroe == null)
                return HttpNotFound();
            if (like == null)
            {
                like = new Like()
                {
                    Id = db.Likes.Count() + 1,
                    like = true,
                    UserName = User.Identity.Name,
                    HeroeId = heroeId,
                    MovieId = null
                };
                heroe.Likes.Add(like);
                db.SaveChanges();
            }
            else
            {
                if (like.like)
                {
                    db.Likes.Remove(like);
                    db.SaveChanges();
                }
                else
                {
                    db.Likes.Remove(like);
                    like = new Like()
                    {
                        Id = db.Likes.Count() + 1,
                        like = true,
                        UserName = User.Identity.Name,
                        HeroeId = heroeId,
                        MovieId = null
                    };
                    heroe.Likes.Add(like);
                    db.SaveChanges();
                }
            }
            return PartialView("LikeHeroe", heroe);
        }
        [HttpPost]
        public ActionResult DislikeHeroe(int? heroeId)
        {
            User user = null;
            using (UserContext db = new UserContext())
            {
                user = db.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            }
            if (user == null)
            {
                return Json(new { url = Url.Action("Login", "Account") });
            }
            Like like = db.Likes.Where(l => l.UserName == User.Identity.Name).FirstOrDefault();
            Heroe heroe = db.Heroes.Find(heroeId);
            if (heroe == null)
                return HttpNotFound();
            if (like == null)
            {
                like = new Like()
                {
                    Id = db.Likes.Count() + 1,
                    like = false,
                    UserName = User.Identity.Name,
                    HeroeId = heroeId,
                    MovieId = null
                };
                heroe.Likes.Add(like);
                db.SaveChanges();
            }
            else
            {
                if (like.like)
                {
                    db.Likes.Remove(like);
                    like = new Like()
                    {
                        Id = db.Likes.Count() + 1,
                        like = false,
                        UserName = User.Identity.Name,
                        HeroeId = heroeId,
                        MovieId = null
                    };
                    heroe.Likes.Add(like);
                    db.SaveChanges();
                }
                else
                {
                    db.Likes.Remove(like);
                    db.SaveChanges();
                }
            }
            return PartialView("LikeHeroe", heroe);
        }
        [HttpPost]
        public ActionResult LikeMovie(int? movieId)
        {
            User user = null;
            using (UserContext db = new UserContext())
            {
                user = db.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            }
            if (user == null)
            {
                return Json(new { url = Url.Action("Login", "Account") });
            }
            Like like = db.Likes.Where(l => l.UserName == User.Identity.Name).FirstOrDefault();
            Movie movie = db.Movies.Find(movieId);
            if (movie == null)
                return HttpNotFound();
            if (like == null)
            {
                like = new Like()
                {
                    Id = db.Likes.Count() + 1,
                    like = true,
                    UserName = User.Identity.Name,
                    HeroeId = null,
                    MovieId = movieId
                };
                movie.Likes.Add(like);
                db.SaveChanges();
            }
            else
            {
                if (like.like)
                {
                    db.Likes.Remove(like);
                    db.SaveChanges();
                }
                else
                {
                    db.Likes.Remove(like);
                    like = new Like()
                    {
                        Id = db.Likes.Count() + 1,
                        like = true,
                        UserName = User.Identity.Name,
                        HeroeId = null,
                        MovieId = movieId
                    };
                    movie.Likes.Add(like);
                    db.SaveChanges();
                }
            }
            return PartialView("LikeMovie", movie);
        }
        [HttpPost]
        public ActionResult DislikeMovie(int? movieId)
        {
            User user = null;
            using (UserContext db = new UserContext())
            {
                user = db.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            }
            if (user == null)
            {
                return Json(new { url = Url.Action("Login", "Account") });
            }
            Like like = db.Likes.Where(l => l.UserName == User.Identity.Name).FirstOrDefault();
            Movie movie = db.Movies.Find(movieId);
            if (movie == null)
                return HttpNotFound();
            if (like == null)
            {
                like = new Like()
                {

Marvel of the Universe/Views/Marvel/Comment.cshtml
@model Marvel_of_the_Universe.Models.Comment
<div class="col-md-12 text-white bg-danger" style="padding:5px">
    <h3 class="text-left">@Model.UserName</h3>
    <p><h5>@Model.Text</h5></p>
</div>

Marvel of the Universe/Views/Marvel/Heroe.cshtml
@model Marvel_of_the_Universe.Models.ViewHeroe
@using Marvel_of_the_Universe.Helpers
@{

    ViewBag.Title = "Heroe";
}
<script type="text/javascript">
    var onSuccess = function (result) {
        if (result.url) {
            window.location.href = result.url;
        }
    }
</script>
<div class="container-fluid padding">
    <div class="row">
        <div class="col-md-4">
            <img height="385" width="280" src="~/Images/Heroes/@Model.Heroe.Image" class="img-thumbnail" />
        </div>
        <div class="border-white card text-black-50 text-body col-md-8" style="padding:10px;">
            <p><h2 class="text-center text-danger">@Model.Heroe.Name</h2></p>
            <p><h5>Actor: @Model.Heroe.Actor</h5></p>
            <p><h5>Skills: @Model.Heroe.Skills</h5></p>
            <div id="like" class="row mx-auto">
                <h4 style="padding:5px">@Model.Heroe.Likes.Where(c => c.like == true).Count()</h4>
                @using (Ajax.BeginForm("LikeHeroe", "Marvel", new AjaxOptions { UpdateTargetId = "like", HttpMethod = "POST", OnSuccess ="onSuccess" }))
                {
                    @Html.Hidden("HeroeId", Model.Heroe.Id)
                    <button type="submit">
                        <img src="~/Images/Like/Like.png" width="35" height="35" />
                    </button>
                }
                <h4 style="padding:5px">@Model.Heroe.Likes.Where(c => c.like == false).Count()</h4>
                @using (Ajax.BeginForm("DislikeHeroe", "Marvel", new AjaxOptions { UpdateTargetId = "like", HttpMethod = "POST", OnSuccess = "onSuccess" }))
                {
                    @Html.Hidden("HeroeId", Model.Heroe.Id)
                    <button type="submit">
                        <img src="~/Images/Like/Dislike.png" width="35" height="35" />
                    </button>
                }
            </div>
        </div>
    </div>
    <div id="movies">
        <div class="row">
            @foreach (var item in Model.Movies.Take(3))
            {
                <div class="card-group col-md-4" style="padding:10px;">
                    <div class="card text-danger border-danger ">
                        <a href="@Url.Action("Movie","Marvel", new { id = item.Id})"><img height="350" width="140" href="Marvel/Heroe" src="~/Images/Movies/@item.Image" class="card-img-top figure-img" /></a>
                        <h5 class="card-title text-center">@Html.DisplayFor(modelItem => item.Name)</h5>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="row mx-auto">
        <div class="btn-group mx-auto">
            @{
                int link = 1;
                while (link <= Model.ListInfo.TotalList)
                {
                    @Ajax.ActionLink(
                        link.ToString(),
                        "ListMovies",
                        "Marvel",
                        new { heroeId = Model.Heroe.Id, list = link },
                        new AjaxOptions { UpdateTargetId = "movies", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" },
                        new { @class = "btn btn-danger" });
                    link++;
                }
            }
        </div>
    </div>
    <div id="comments" class="row">
        @{
            foreach (var comment in Model.Heroe.Comments)
            {
                <div class="col-md-12 text-white bg-danger" style="margin:5px">
                    <h3 class="text-left">@comment.UserName</h3>
                    <p><h5>@comment.Text</h5></p>
                </div>
            }
        }
    </div>
    @using (Ajax.BeginForm("NewComment", "Marvel", new AjaxOptions { UpdateTargetId = "comments", HttpMethod = "POST", InsertionMode = InsertionMode.InsertAfter, OnSuccess = "onSuccess" }))
    {
        @Html.Hidden("Id", Model.Heroe.Comments.Count + 1)
        @Html.TextArea("Text", "Comment", 5, 200, null)
        @Html.Hidden("UserName", User.Identity.Name)
        @Html.Hidden("HeroeId", Model.Heroe.Id)
        @Html.Hidden("MovieId", null)
        <input type="submit" value="Send" class="text-danger">
    }
</div>

Marvel of the Universe/Views/Marvel/Heroes.cshtml
@model Marvel_of_the_Universe.Models.IndexViewHeroes
@using Marvel_of_the_Universe.Helpers;
<link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
@{
    ViewBag.Title = "Heroes";
}
<div class="container-fluid padding">
    <div class="row">
        @foreach (var item in Model.Heroes)
        {
            <div class="card-group col-md-4" style="padding:10px;">
                <div class="card text-danger border-danger ">
                    <a href="Heroe/@item.Id"><img height="350" width="140" href="Marvel/Heroe" src="~/Images/Heroes/@item.Image" class="card-img-top figure-img" /></a>
                    <h5 class="card-title text-center">@Html.DisplayFor(modelItem => item.Name)</h5>
                </div>
            </div>
        }
    </div>
</div>
<div class="row mx-auto">
    <div class="btn-group mx-auto">
        @Html.PageLinks(Model.PageInfo, x => Url.Action("Heroes", "Marvel", new { page = x }))
    </div>
</div>

Marvel of the Universe/Views/Marvel/Index.cshtml
@{
    ViewBag.Title = "Marvel";
}
<div class="container-fluid padding">
    <div class="container col-md-12">
        <div class="card text-info border-white ">
            <img src="/Marvel/GetImage" class="card-img-bottom figure-img" />
            <h4 class="text-center text-danger">Welcome to the Marvel of the Universe</h4>
        </div>
    </div>
    <div class="container col-md-12">

        <p>
            <h5 class="text-body text-info">
                The site is intended for fans of the marvels of Marvel. Here you can:
            </h5>
                <ul class="text-info text-body">
                    <li>view the abilities of any heroe</li>
                    <li>find out history and information heroe</li>
                    <li>view all the films where the hero has participated</li>
                </ul>
        </p>
        <p>
            <h5 class="text-body text-info">
                For registered users added additional features such as
            </h5>
            <ul class="text-info text-body">
                <li>comments to the heroes or films</li>
                <li>like heroes or films</li>
                <li>to look over like heroe or movie in your personal office</li>
            </ul>
            View the abilities of any heroe and all the information about him. You can also view all the films where the hero has participated. For registered users added additional features such as: comments to the hero or film and liki.
        </p>
    </div>
</div>

Marvel of the Universe/Views/Marvel/LikeHeroe.cshtml
@model Marvel_of_the_Universe.Models.Heroe

<h4 style="padding:5px">@Model.Likes.Where(c => c.like == true).Count()</h4>
@using (Ajax.BeginForm("LikeHeroe", "Marvel", new AjaxOptions { UpdateTargetId = "like", HttpMethod = "POST" }))
{
    @Html.Hidden("HeroeId", Model.Id)
    <button type="submit">
        <img src="~/Images/Like/Like.png" width="35" height="35" />
    </button>
}
<h4 style="padding:5px"> @Model.Likes.Where(c => c.like == false).Count() </h4>
@using (Ajax.BeginForm("DislikeHeroe", "Marvel", new AjaxOptions { UpdateTargetId = "like", HttpMethod = "POST" }))
{
    @Html.Hidden("HeroeId", Model.Id)
    <button type="submit">
        <img src="~/Images/Like/Dislike.png" width="35" height="35" />
    </button>
}

Marvel of the Universe/Views/Marvel/LikeMovie.cshtml
@model Marvel_of_the_Universe.Models.Movie
<h4 style="padding:5px">@Model.Likes.Where(c => c.like == true).Count()</h4>
@using (Ajax.BeginForm("LikeMovie", "Marvel", new AjaxOptions { UpdateTargetId = "like", HttpMethod = "POST" }))
{
    @Html.Hidden("MovieId", Model.Id)
    <button type="submit">
        <img src="~/Images/Like/Like.png" width="35" height="35" />
    </button>
}
<h4 style="padding:5px"> @Model.Likes.Where(c => c.like == false).Count() </h4>
@using (Ajax.BeginForm("DislikeMovie", "Marvel", new AjaxOptions { UpdateTargetId = "like", HttpMethod = "POST" }))
{
    @Html.Hidden("MovieId", Model.Id)
    <button type="submit">
        <img src="~/Images/Like/Dislike.png" width="35" height="35" />
    </button>
}

Marvel of the Universe/Views/Marvel/ListHeroes.cshtml
@model IEnumerable<Marvel_of_the_Universe.Models.Heroe>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="card-group col-md-4" style="padding:10px;">
            <div class="card text-danger border-danger ">
                <a href="@Url.Action("Heroe","Marvel", new { id = item.Id})"><img height="350" width="140" src="~/Images/Heroes/@item.Image" class="card-img-top figure-img" /></a>
                <h5 class="card-title text-center">@Html.DisplayFor(modelItem => item.Name)</h5>
            </div>
        </div>
    }
</div>

Marvel of the Universe/Views/Marvel/ListMovies.cshtml
@model IEnumerable<Marvel_of_the_Universe.Models.Movie>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="card-group col-md-4" style="padding:10px;">
            <div class="card text-danger border-danger ">
                <a href="@Url.Action("Movie","Marvel", new { id = item.Id})"><img height="350" width="140"  src="~/Images/Movies/@item.Image" class="card-img-top figure-img" /></a>
                <h5 class="card-title text-center">@Html.DisplayFor(modelItem => item.Name)</h5>
            </div>
        </div>
    }
</div>

Marvel of the Universe/Views/Marvel/Movie.cshtml
@model Marvel_of_the_Universe.Models.ViewMovie
@{
    ViewBag.Title = Model.Movie.Name;
}
<script type="text/javascript">
    var onSuccess = function (result) {
        if (result.url) {
            window.location.href = result.url;
        }
    }
</script>
<div class="container-fluid padding">
    <div class="row">
        <div class=" col-md-4">
            <img height="375" width="280" src="~/Images/Movies/@Model.Movie.Image" class="img-thumbnail" />
        </div>
        <div class="border-white card text-black-50 text-body col-md-8" style="padding:10px;">
            <p><h2 class="text-center text-danger">@Model.Movie.Name</h2></p>
            <p><h5>Genre: @Model.Movie.Genre</h5></p>
            <p><h5>Year release: @Model.Movie.YearRelease</h5></p>
            <div id="like" class="row mx-auto">
                <h4 style="padding:5px">@Model.Movie.Likes.Where(c => c.like == true).Count()</h4>
                @using (Ajax.BeginForm("LikeMovie", "Marvel", new AjaxOptions { UpdateTargetId = "like", HttpMethod = "POST", OnSuccess = "onSuccess" }))
                {
                    @Html.Hidden("MovieId", Model.Movie.Id)
                    <button type="submit">
                        <img src="~/Images/Like/Like.png" width="35" height="35" />
                    </button>
                }
                <h4 style="padding:5px">@Model.Movie.Likes.Where(c => c.like == false).Count()</h4>
                @using (Ajax.BeginForm("DislikeMovie", "Marvel", new AjaxOptions { UpdateTargetId = "like", HttpMethod = "POST", OnSuccess = "onSuccess" }))
                {
                    @Html.Hidden("MovieId", Model.Movie.Id)
                    <button type="submit">
                        <img src="~/Images/Like/Dislike.png" width="35" height="35" />
                    </button>
                }
            </div>
        </div>
    </div>
    <div id="heroes">
        <div class="row">
            @foreach (var item in Model.Heroes)
            {
                <div class="card-group col-md-4" style="padding:10px;">
                    <div class="card text-danger border-danger ">
                        <a href="@Url.Action("Heroe","Marvel", new { id = item.Id})"><img height="350" width="140"  src="~/Images/Heroes/@item.Image" class="card-img-top figure-img" /></a>
                        <h5 class="card-title text-center">@Html.DisplayFor(modelItem => item.Name)</h5>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="row mx-auto">
        <div class="btn-group mx-auto">
            @{
                int link = 1;
                while (link <= Model.ListInfo.TotalList)
                {
                    @Ajax.ActionLink(
                        link.ToString(),
                        "ListHeroes",
                        "Marvel",
                        new { movieId = Model.Movie.Id, list = link },
                        new AjaxOptions { UpdateTargetId = "heroes", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" },
                        new { @class = "btn btn-danger" });
                    link++;
                }
            }
        </div>
    </div>
    <div id="comments" class="row">
        @{
            foreach (var comment in Model.Movie.Comments)
            {
                <div class="col-md-12 text-white bg-danger" style="margin:5px">
                    <h3 class="text-left">@comment.UserName</h3>
                    <p><h5>@comment.Text</h5></p>
                </div>
            }
        }
    </div>
    @using (Ajax.BeginForm("NewComment", "Marvel", new AjaxOptions { UpdateTargetId = "comments", HttpMethod = "POST", InsertionMode = InsertionMode.InsertAfter, OnSuccess = "onSuccess" }))
    {
        @Html.Hidden("Id", Model.Movie.Comments.Count + 1)
        @Html.TextArea("Text", "Comment", 5, 200, null)
        @Html.Hidden("UserName", User.Identity.Name)
        @Html.Hidden("HeroeId", null)
        @Html.Hidden("MovieId", Model.Movie.Id)
        <input type="submit" value="Send" class="text-danger">
    }
</div>

Marvel of the Universe/Views/Marvel/Movies.cshtml
@model Marvel_of_the_Universe.Models.IndexViewMovies
@using Marvel_of_the_Universe.Helpers;
<link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
@{
    ViewBag.Title = "Movies";
}
<div class="container-fluid padding">
    <div class="row">
        @foreach (var item in Model.Movies)
        {
            <div class="card-group col-md-4" style="padding:10px;">
                <div class="card text-danger border-danger ">
                    <a href="Heroe/@item.Id"><img height="350" width="140" href="Marvel/Heroe" src="~/Images/Movies/@item.Image" class="card-img-top figure-img" /></a>
                    <h5 class="card-title text-center">@Html.DisplayFor(modelItem => item.Name)</h5>
                </div>
            </div>
        }
    </div>
</div>
<div class="row mx-auto">
    <div class="btn-group mx-auto">
        @Html.PageLinks(Model.PageInfo, x => Url.Action("Movies", "Marvel", new { page = x }))
    </div>
</div>